package predictor

data class CheckupFeatures(
    val age: Int,
    val nationality: String,
    val placeOfBirth: String,
    val previousPlaceOfLiving: String,
    val biteType: String,
    val healthGroup: Int,
    val sumHygieneIndex: Int,
    val toothErosion: Int,
    val toothErosionCount: Int,
    val dentalTrauma: Int,
    val dentalTraumaCount: Int,
    val numIntact: Int,
    val numCaries: Int,
    val numFillingWithCaries: Int,
    val numFillingWithoutCaries: Int,
    val numRemovalCaries: Int,
    val numRemovalOtherReason: Int,
    val numSealedFissure: Int,
    val numVeneer: Int,
    val numImpacted: Int,
    val numNotRegistered: Int,
    val numIntactTemp: Int,
    val numCariesTemp: Int,
    val numFillingWithCariesTemp: Int,
    val numFillingWithoutCariesTemp: Int,
    val numRemovalCariesTemp: Int,
    val numSealedFissureTemp: Int,
    val numVeneerTemp: Int,
    val jointSymptoms: Int,
    val jointClicking: Int,
    val jointSoreness: Int,
    val jointLimitation: Int,
    val cpu: Int
)
